version: '3.1'

services:

  db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 15432:5432

  adminer:
    image: adminer
    ports:
      - 8001:8000

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host=0.0.0.0
    ports:
      - 8000:8000
